### ISSUE TITLE
Swift 1.2

### ISSUE THREAD

**Issue by andersonkxiass** [BenjaminPrieur/IOStickyHeader#1]
Congratulations on your initiative to make the port to Swift 2.0. I know it may seem strange but it would be interesting to be able to also use with Swift 1.2 as the version 2.0 is still in beta. So we could use in projects in production.

**Comment by BenjaminPrieur** [comment]
New branch created with swift 1.2. I tested it quickly, it seems to work well.
I hope it helps you.

**Comment by BenjaminPrieur** [comment]
``` ruby
use_frameworks!
pod 'IOStickyHeader', :git => 'https://github.com/BenjaminPrieur/IOStickyHeader.git', :branch => 'Swift1.2'
```

**Comment by andersonkxiass** [comment]
Thanks, I'll test on my project!
