### ISSUE TITLE
Carthage Update not Working 

### ISSUE THREAD

**Issue by andre991** [BenjaminPrieur/IOStickyHeader#18]
<img width="569" alt="captura de tela 2016-11-23 as 16 16 27" src="https://cloud.githubusercontent.com/assets/8302454/20573766/939dcefa-b198-11e6-82ac-5324dbbe122f.png">

**Comment by BenjaminPrieur** [comment]
which command line did you do?

**Comment by andre991** [comment]
carthage update --platform ios

**Comment by BenjaminPrieur** [comment]
my bad, release 1.0.2 had .gitmodule which has been deleted after the release.
I bumped release number and it should work.

**Comment by andre991** [comment]
thank you so much!!! ;) It's working!.
