### ISSUE TITLE
xcode6.4 build failed 

### ISSUE THREAD

**Issue by MrBoog** [BenjaminPrieur/IOStickyHeader#2]
can't compile IOStickyHeaderParallaxHeader.swift.

**Comment by BenjaminPrieur** [comment]
Can you tell me which version of swift doesn't compile

**Comment by BenjaminPrieur** [comment]
I did not see you use xCode6.4 so did you pull branch Swift1.2?
pod 'IOStickyHeader', :git => 'https://github.com/BenjaminPrieur/IOStickyHeader.git', :branch => 'Swift1.2'
