### ISSUE TITLE
Example project: image missing

### ISSUE THREAD

**Issue by oonoo** [BenjaminPrieur/IOStickyHeader#3]
The asset catalogue is empty and referenced images like "photo1" can not load.

**Comment by BenjaminPrieur** [comment]
Sry i forgot to add some assets to my last commit :/
I fixed it this week end

**Comment by BenjaminPrieur** [comment]
Sorry I was a little long to push a new release.
I fixed the missing image.
If you find some other mistake... keep me posted ;)
