### ISSUE TITLE
warning occurs at runtime

### ISSUE THREAD

**Issue by hengchengfei** [BenjaminPrieur/IOStickyHeader#5]
Warning:

<p><b>This is likely occurring because the flow layout subclass eval.IOStickyHeaderFlowLayout is modifying attributes returned by UICollectionViewFlowLayout without copying them
</b></p>

</p>

IOStickyHeaderFlowLayout.swift

<pre><code>
public override func layoutAttributesForItemAtIndexPath(indexPath: NSIndexPath) -> UICollectionViewLayoutAttributes? {
        let attributes = super.layoutAttributesForItemAtIndexPath(indexPath)
        var frame = attributes?.frame
        frame!.origin.y += (self.parallaxHeaderReferenceSize?.height)!
        attributes?.frame = frame!
        return attributes
}
</code></pre>

[http://stackoverflow.com/questions/31771089/when-using-subclassed-collectionviewflowlayout-im-getting-weird-error]()

**Comment by BenjaminPrieur** [comment]
I can't reproduce your warning.
Did you get the warning with the example project or your project?
Which version of swift are you using?
I updated my pod may be i solved it

**Comment by hengchengfei** [comment]
XCode7.1 Swift2.1

it occurs in my project.

I appreciate.

**Comment by Bragegs** [comment]
Hi!
I could not reproduce the stackoverflow answer, do you mind sharing your solution here?

**Comment by Bragegs** [comment]
in layoutAttributesForElementsInRect(rect: CGRect)
replace this line
var allItems = super.layoutAttributesForElementsInRect(rect)!

with this, removed the warning for me:

var allItems = [ UICollectionViewLayoutAttributes ]()
let attributes = super.layoutAttributesForElementsInRect(adjustedRec)
        for originalAttribute in  attributes! {
            allItems.append(originalAttribute.copy() as! UICollectionViewLayoutAttributes)
        }
