### ISSUE TITLE
Not sure what the issue is but I'm getting nan for progressiveness

### ISSUE THREAD

**Issue by phongleq** [BenjaminPrieur/IOStickyHeader#6]
Im trying to replicate the demo and keep getting nan for progressiveness in my header view.

**Comment by BenjaminPrieur** [comment]
are you trying to do a division by 0?
can you share your code where you get this "nan"?

**Comment by phongleq** [comment]
Im not doing any logic, I have a cel header that is doing this `self.imageWidthConstraint.constant = self.maxWidth! * layoutAttributes.progressiveness` and the what I get back from progressiveness is nan and inf if i check for nan

**Comment by BenjaminPrieur** [comment]
I can't reproduce.
Can you create a sample project on github?
Do you have the same issue with the sample project?
