### ISSUE TITLE
Swift 2.0 Issue

### ISSUE THREAD

**Issue by northern-dom** [BenjaminPrieur/IOStickyHeader#7]
Hi, Awesome port of this class. Seems to be a slight issue with Xcode 7 and Swift 2.0. When I re-layout the views in a device rotation I get a warning when calling layoutAttributesForElementsInRect about not copying the attributes first. After a bit of investigation and a work around is to iterate through all the attributes and copy them into a new array....a follows:

```
public override func layoutAttributesForElementsInRect(rect: CGRect) -> [UICollectionViewLayoutAttributes]? {
    var adjustedRec = rect
    adjustedRec.origin.y -= (self.parallaxHeaderReferenceSize?.height)!
    // Don't copy like this....
    // var allItems: [UICollectionViewLayoutAttributes] = super.layoutAttributesForElementsInRect(adjustedRec)!


    // Instead copy like this for Xcode 7 Fix 
    let attributes = super.layoutAttributesForElementsInRect(adjustedRec)
    var allItems = [UICollectionViewLayoutAttributes]()

    for itemAttributes in attributes! {
        let itemAttributesCopy = itemAttributes.copy() as! UICollectionViewLayoutAttributes
        // manipulate itemAttributesCopy
        allItems.append(itemAttributesCopy)
    }

 // Remainder of your code....
```

Hope this helps! Many thanks for your port. Great stuff! 

Dom

**Comment by BenjaminPrieur** [comment]
Thx for your feedback!
I ll fixed it.

**Comment by BenjaminPrieur** [comment]
Pod updated!
You can play with it ;)

P.S. : project updated to swift 2.1 on Master. I ll create another branch for 2.0
